Documentation:
  Enabled: false
Style/For:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false


