require 'rubocop/rake_task'
require 'rspec/core/rake_test'

RSpec::Core::RakeTask.new(:rspec) do |test|
  test.pattern = 'spec/**/*_spec.rb'
  test.rspec_opts = ['--format documentation']
end

RuboCop::RakeTask.new(:rubocop) do |test|
  test.options = ['--display-cop-names']
end

task :all do
  Rake::Task['rspec'].execute
  Rake::Task['rubocop'].execute
end
